# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obbkit < Formula
  desc ""
  homepage "https://github.com/AdeboyeDN/obbkit"
  version "0.0.2"

  on_macos do
    url "https://github.com/AdeboyeDN/obbkit/releases/download/v0.0.2/obbkit_0.0.2_Darwin_all.tar.gz"
    sha256 "103a8f8939c413b5d9abc427bb00d110390b864bcbd4ec17f9f14c3349111d0b"

    def install
      bin.install "obbkit"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AdeboyeDN/obbkit/releases/download/v0.0.2/obbkit_0.0.2_Linux_arm64.tar.gz"
      sha256 "6d699473af22e98f705f6c053649a89bf1b5f539aff008383e12b950f6e3d71d"

      def install
        bin.install "obbkit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AdeboyeDN/obbkit/releases/download/v0.0.2/obbkit_0.0.2_Linux_x86_64.tar.gz"
      sha256 "bb7c86d1702440a4b2f0e287423be8cca49885600b29bf415a43d4622e0f3744"

      def install
        bin.install "obbkit"
      end
    end
  end
end
