# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obbkit < Formula
  desc ""
  homepage "https://github.com/AdeboyeDN/obbkit"
  version "0.0.1"

  on_macos do
    url "https://github.com/AdeboyeDN/obbkit/releases/download/v0.0.1/obbkit_0.0.1_Darwin_all.tar.gz"
    sha256 "d47dcb7f3bcb44985de0b04f54a8098df8e894a13d0eaf978640a9e911919a29"

    def install
      bin.install "obbkit"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AdeboyeDN/obbkit/releases/download/v0.0.1/obbkit_0.0.1_Linux_arm64.tar.gz"
      sha256 "c43e4428ca161ed58546a24bca41e4ae90d5be87656145dd0a3039cfd070e643"

      def install
        bin.install "obbkit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AdeboyeDN/obbkit/releases/download/v0.0.1/obbkit_0.0.1_Linux_x86_64.tar.gz"
      sha256 "ec2bdb4dc54db0a97ba1ced9040713bcf7a7cd8f289418484cab684d0ebf9a20"

      def install
        bin.install "obbkit"
      end
    end
  end
end
